export const PermissionCodes = {
  ProjectRead: 'Project.Read',
  ProjectCreate: 'Project.Create',
  ProjectUpdate: 'Project.Update',
  ProjectDelete: 'Project.Delete',
  MemberRead: 'Member.Read',
  MemberInvite: 'Member.Invite',
  MemberRemove: 'Member.Remove',
  MemberChangeRole: 'Member.ChangeRole',
  FlowRead: 'Flow.Read',
  FlowCreate: 'Flow.Create',
  FlowUpdate: 'Flow.Update',
  FlowDelete: 'Flow.Delete',
  VersionRead: 'Version.Read',
  VersionCreate: 'Version.Create',
  VersionRestore: 'Version.Restore',
  VersionDelete: 'Version.Delete',
  NodeUpdate: 'Node.Update',
  LinkUpdate: 'Link.Update',
  CommentUpdate: 'Comment.Update',
  ImageRead: 'Image.Read',
  ImageUpload: 'Image.Upload',
  ImageUpdate: 'Image.Update',
  ImageDelete: 'Image.Delete',
  TemplateRead: 'Template.Read',
  TemplateApply: 'Template.Apply',
  TemplateCreate: 'Template.Create',
  TemplateUpdate: 'Template.Update',
  TemplateDelete: 'Template.Delete',
  ExportExecute: 'Export.Execute',
  SettingUserUpdate: 'Setting.UserUpdate',
  SettingProjectUpdate: 'Setting.ProjectUpdate',
  SettingEditorUpdate: 'Setting.EditorUpdate',
  SettingAiUpdate: 'Setting.AiUpdate',
  SettingExportUpdate: 'Setting.ExportUpdate',
} as const

export type PermissionCode = typeof PermissionCodes[keyof typeof PermissionCodes]
