<script setup lang="ts">
import { computed, onMounted, reactive, ref } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import Button from 'primevue/button'; import Dialog from 'primevue/dialog'; import MainLayout from '../layouts/MainLayout.vue'
import { createTransportManufacturerVehicleType, deleteTransportManufacturerVehicleType, fetchTransportManufacturers, fetchTransportManufacturerVehicleTypes, updateTransportManufacturerVehicleType } from '../api/transportApi'
import type { TransportManufacturer, TransportManufacturerVehicleType, VehicleType } from '../types/transport'
const route=useRoute(),router=useRouter(),manufacturerId=String(route.params.manufacturerId)
const manufacturers=ref<TransportManufacturer[]>([]),items=ref<TransportManufacturerVehicleType[]>([]),dialogVisible=ref(false),saving=ref(false),editingId=ref<string|null>(null),error=ref<string|null>(null)
const form=reactive({vehicleType:'AGF' as VehicleType,description:'',sortOrder:null as number|null,isActive:true})
const manufacturer=computed(()=>manufacturers.value.find(x=>x.manufacturerId===manufacturerId)??null)
const visibleItems=computed(()=>items.value.filter(x=>x.manufacturerId===manufacturerId))
const msg=(e:unknown,f:string)=>e instanceof Error?e.message:f
async function load(){try{[manufacturers.value,items.value]=await Promise.all([fetchTransportManufacturers(),fetchTransportManufacturerVehicleTypes(true)])}catch(e){error.value=msg(e,'種別の取得に失敗しました。')}}
function open(item?:TransportManufacturerVehicleType){editingId.value=item?.manufacturerVehicleTypeId??null;Object.assign(form,{vehicleType:item?.vehicleType??'AGF',description:item?.description??'',sortOrder:item?.sortOrder??null,isActive:item?.isActive??true});error.value=null;dialogVisible.value=true}
async function save(){saving.value=true;try{const request={...form,description:form.description.trim()||null};editingId.value?await updateTransportManufacturerVehicleType(editingId.value,request):await createTransportManufacturerVehicleType(manufacturerId,request);dialogVisible.value=false;await load()}catch(e){error.value=msg(e,'種別の保存に失敗しました。')}finally{saving.value=false}}
async function remove(item:TransportManufacturerVehicleType){if(!confirm(`種別「${item.vehicleType}」を削除しますか？`))return;try{await deleteTransportManufacturerVehicleType(item.manufacturerVehicleTypeId);await load()}catch(e){error.value=msg(e,'種別の削除に失敗しました。')}}
function showCommands(item:TransportManufacturerVehicleType){router.push({name:'transport-commands',params:{manufacturerId,typeId:item.manufacturerVehicleTypeId}})}
onMounted(load)
</script>
<template><MainLayout><section class="page master-page"><div class="breadcrumbs"><RouterLink :to="{name:'transport-manufacturers'}">メーカー一覧</RouterLink><span>›</span><strong>{{ manufacturer?.name??'メーカー' }}</strong></div><header class="card page-header"><div><Button label="メーカー一覧へ戻る" icon="pi pi-arrow-left" text @click="router.push({name:'transport-manufacturers'})"/><h1>{{ manufacturer?.name }} のAGF・AGV</h1><p>このメーカーが対応する種別を選択してください。</p></div><Button label="AGF・AGVを追加" icon="pi pi-plus" @click="open()"/></header><p v-if="error" class="error">{{ error }}</p><section class="card list-card"><div class="list-header"><strong>対応種別</strong><span>{{ visibleItems.length }}件</span></div><p v-if="!visibleItems.length" class="empty">AGF・AGV種別がありません。</p><button v-for="item in visibleItems" :key="item.manufacturerVehicleTypeId" class="master-row" @click="showCommands(item)"><span class="type-mark">{{ item.vehicleType }}</span><span class="row-main"><strong>{{ item.vehicleType }}</strong><small>{{ item.description||'説明なし' }}</small></span><span class="status" :class="{inactive:!item.isActive}">{{ item.isActive?'有効':'無効' }}</span><span class="actions"><Button icon="pi pi-pencil" text rounded @click.stop="open(item)"/><Button icon="pi pi-trash" text rounded severity="danger" @click.stop="remove(item)"/><i class="pi pi-chevron-right"/></span></button></section><Dialog v-model:visible="dialogVisible" modal :header="editingId?'種別を編集':'AGF・AGVを追加'" :style="{width:'min(520px,92vw)'}"><div class="context">{{ manufacturer?.name }}</div><div class="form"><label>種別<select v-model="form.vehicleType" :disabled="!!editingId"><option value="AGF">AGF</option><option value="AGV">AGV</option></select></label><label>説明<textarea v-model="form.description" rows="3"/></label><label>表示順<input v-model.number="form.sortOrder" type="number"/></label><label class="check"><input v-model="form.isActive" type="checkbox"/>有効にする</label><p v-if="error" class="error">{{ error }}</p></div><template #footer><Button label="キャンセル" text severity="secondary" @click="dialogVisible=false"/><Button label="保存" :loading="saving" @click="save"/></template></Dialog></section></MainLayout></template>
<style scoped src="./transport-master-page.css"></style>
