// <auto-generated />
using System;
using FlowDesigner.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlowDesigner.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Auth.AuditLog", b =>
                {
                    b.Property<Guid>("AuditLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Detail")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("AuditLogId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("AUDIT_LOG", (string)null);
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Auth.Permission", b =>
                {
                    b.Property<Guid>("PermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("PermissionCode")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("PermissionId");

                    b.HasIndex("PermissionCode")
                        .IsUnique();

                    b.ToTable("PERMISSION", (string)null);
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Auth.ProjectInvite", b =>
                {
                    b.Property<Guid>("ProjectInviteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("InvitedByUserId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectInviteId");

                    b.HasIndex("InvitedByUserId");

                    b.HasIndex("ProjectId", "Email", "Status");

                    b.ToTable("PROJECT_INVITE", (string)null);
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Auth.ProjectMember", b =>
                {
                    b.Property<Guid>("ProjectMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("JoinedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectMemberId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.HasIndex("ProjectId", "UserId")
                        .IsUnique();

                    b.ToTable("PROJECT_MEMBER", (string)null);
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Auth.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId");

                    b.HasIndex("RoleCode")
                        .IsUnique();

                    b.ToTable("ROLE", (string)null);
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Auth.RolePermission", b =>
                {
                    b.Property<Guid>("RolePermissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("RolePermissionId");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("ROLE_PERMISSION", (string)null);
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Auth.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("GitHubId")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("GitHubId")
                        .IsUnique();

                    b.ToTable("USER_ACCOUNT", (string)null);
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Core.Flow", b =>
                {
                    b.Property<Guid>("FlowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("FlowId");

                    b.HasIndex("ProjectId", "Name")
                        .IsUnique();

                    b.ToTable("FLOW", (string)null);
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Core.FlowComment", b =>
                {
                    b.Property<Guid>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("NodeId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<double>("X")
                        .HasColumnType("REAL");

                    b.Property<double>("Y")
                        .HasColumnType("REAL");

                    b.HasKey("CommentId");

                    b.HasIndex("FlowId");

                    b.HasIndex("NodeId");

                    b.ToTable("COMMENT", (string)null);
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Core.FlowImage", b =>
                {
                    b.Property<Guid>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSize")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("FlowId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UploadedAtUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("ImageId");

                    b.HasIndex("FlowId");

                    b.HasIndex("ProjectId");

                    b.ToTable("IMAGE", (string)null);
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Core.FlowLink", b =>
                {
                    b.Property<Guid>("LinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Condition")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Label")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("SourceNodeId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TargetNodeId")
                        .HasColumnType("TEXT");

                    b.HasKey("LinkId");

                    b.HasIndex("FlowId");

                    b.HasIndex("SourceNodeId");

                    b.HasIndex("TargetNodeId");

                    b.ToTable("LINK", (string)null);
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Core.FlowMetadata", b =>
                {
                    b.Property<Guid>("MetadataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaKey")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetaValue")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.HasKey("MetadataId");

                    b.HasIndex("FlowId", "MetaKey")
                        .IsUnique();

                    b.ToTable("METADATA", (string)null);
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Core.FlowNode", b =>
                {
                    b.Property<Guid>("NodeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("LaneId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NodeType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("StageId")
                        .HasColumnType("TEXT");

                    b.Property<double>("X")
                        .HasColumnType("REAL");

                    b.Property<double>("Y")
                        .HasColumnType("REAL");

                    b.HasKey("NodeId");

                    b.HasIndex("FlowId");

                    b.HasIndex("LaneId");

                    b.HasIndex("StageId");

                    b.ToTable("NODE", (string)null);
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Core.FlowVersion", b =>
                {
                    b.Property<Guid>("VersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT");

                    b.Property<string>("SnapshotJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER");

                    b.HasKey("VersionId");

                    b.HasIndex("FlowId", "VersionNumber")
                        .IsUnique();

                    b.ToTable("VERSION", (string)null);
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Core.Lane", b =>
                {
                    b.Property<Guid>("LaneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("FlowId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("LaneId");

                    b.HasIndex("FlowId", "SortOrder")
                        .IsUnique();

                    b.ToTable("LANE", (string)null);
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Core.Project", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("PROJECT_ID");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("CREATED_AT_UTC");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("DESCRIPTION");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("NAME");

                    b.HasKey("ProjectId");

                    b.ToTable("PROJECT", (string)null);
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Core.Stage", b =>
                {
                    b.Property<Guid>("StageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LaneId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER");

                    b.HasKey("StageId");

                    b.HasIndex("LaneId", "SortOrder")
                        .IsUnique();

                    b.ToTable("STAGE", (string)null);
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Settings.AiSetting", b =>
                {
                    b.Property<Guid>("AiSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoReviewEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("AiSettingId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId", "ProjectId")
                        .IsUnique();

                    b.ToTable("AI_SETTING", (string)null);
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Settings.EditorSetting", b =>
                {
                    b.Property<Guid>("EditorSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("GridEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SnapEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("EditorSettingId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId", "ProjectId")
                        .IsUnique();

                    b.ToTable("EDITOR_SETTING", (string)null);
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Settings.ExportSetting", b =>
                {
                    b.Property<Guid>("ExportSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("DefaultFormat")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IncludeMetadata")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("ExportSettingId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId", "ProjectId")
                        .IsUnique();

                    b.ToTable("EXPORT_SETTING", (string)null);
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Settings.ProjectSetting", b =>
                {
                    b.Property<Guid>("ProjectSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AutoSaveEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AutoSaveIntervalSec")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectSettingId");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("PROJECT_SETTING", (string)null);
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Settings.UserSetting", b =>
                {
                    b.Property<Guid>("UserSettingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Theme")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserSettingId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("USER_SETTING", (string)null);
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Auth.AuditLog", b =>
                {
                    b.HasOne("FlowDesigner.Domain.Entities.Core.Project", "Project")
                        .WithMany("AuditLogs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FlowDesigner.Domain.Entities.Auth.User", "User")
                        .WithMany("AuditLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Auth.ProjectInvite", b =>
                {
                    b.HasOne("FlowDesigner.Domain.Entities.Auth.User", "InvitedByUser")
                        .WithMany("ProjectInvites")
                        .HasForeignKey("InvitedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlowDesigner.Domain.Entities.Core.Project", "Project")
                        .WithMany("ProjectInvites")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InvitedByUser");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Auth.ProjectMember", b =>
                {
                    b.HasOne("FlowDesigner.Domain.Entities.Core.Project", "Project")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowDesigner.Domain.Entities.Auth.Role", "Role")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlowDesigner.Domain.Entities.Auth.User", "User")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Auth.RolePermission", b =>
                {
                    b.HasOne("FlowDesigner.Domain.Entities.Auth.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowDesigner.Domain.Entities.Auth.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Core.Flow", b =>
                {
                    b.HasOne("FlowDesigner.Domain.Entities.Core.Project", "Project")
                        .WithMany("Flows")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Core.FlowComment", b =>
                {
                    b.HasOne("FlowDesigner.Domain.Entities.Core.Flow", "Flow")
                        .WithMany("Comments")
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowDesigner.Domain.Entities.Core.FlowNode", "Node")
                        .WithMany()
                        .HasForeignKey("NodeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Flow");

                    b.Navigation("Node");
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Core.FlowImage", b =>
                {
                    b.HasOne("FlowDesigner.Domain.Entities.Core.Flow", "Flow")
                        .WithMany()
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FlowDesigner.Domain.Entities.Core.Project", "Project")
                        .WithMany("Images")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flow");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Core.FlowLink", b =>
                {
                    b.HasOne("FlowDesigner.Domain.Entities.Core.Flow", "Flow")
                        .WithMany("Links")
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowDesigner.Domain.Entities.Core.FlowNode", "SourceNode")
                        .WithMany("OutgoingLinks")
                        .HasForeignKey("SourceNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FlowDesigner.Domain.Entities.Core.FlowNode", "TargetNode")
                        .WithMany("IncomingLinks")
                        .HasForeignKey("TargetNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Flow");

                    b.Navigation("SourceNode");

                    b.Navigation("TargetNode");
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Core.FlowMetadata", b =>
                {
                    b.HasOne("FlowDesigner.Domain.Entities.Core.Flow", "Flow")
                        .WithMany("MetadataItems")
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flow");
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Core.FlowNode", b =>
                {
                    b.HasOne("FlowDesigner.Domain.Entities.Core.Flow", "Flow")
                        .WithMany("Nodes")
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowDesigner.Domain.Entities.Core.Lane", "Lane")
                        .WithMany("Nodes")
                        .HasForeignKey("LaneId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FlowDesigner.Domain.Entities.Core.Stage", "Stage")
                        .WithMany("Nodes")
                        .HasForeignKey("StageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Flow");

                    b.Navigation("Lane");

                    b.Navigation("Stage");
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Core.FlowVersion", b =>
                {
                    b.HasOne("FlowDesigner.Domain.Entities.Core.Flow", "Flow")
                        .WithMany("Versions")
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flow");
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Core.Lane", b =>
                {
                    b.HasOne("FlowDesigner.Domain.Entities.Core.Flow", "Flow")
                        .WithMany("Lanes")
                        .HasForeignKey("FlowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flow");
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Core.Stage", b =>
                {
                    b.HasOne("FlowDesigner.Domain.Entities.Core.Lane", "Lane")
                        .WithMany("Stages")
                        .HasForeignKey("LaneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lane");
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Settings.AiSetting", b =>
                {
                    b.HasOne("FlowDesigner.Domain.Entities.Core.Project", "Project")
                        .WithMany("AiSettings")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowDesigner.Domain.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Settings.EditorSetting", b =>
                {
                    b.HasOne("FlowDesigner.Domain.Entities.Core.Project", "Project")
                        .WithMany("EditorSettings")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowDesigner.Domain.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Settings.ExportSetting", b =>
                {
                    b.HasOne("FlowDesigner.Domain.Entities.Core.Project", "Project")
                        .WithMany("ExportSettings")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FlowDesigner.Domain.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Settings.ProjectSetting", b =>
                {
                    b.HasOne("FlowDesigner.Domain.Entities.Core.Project", "Project")
                        .WithMany("ProjectSettings")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Settings.UserSetting", b =>
                {
                    b.HasOne("FlowDesigner.Domain.Entities.Auth.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Auth.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Auth.Role", b =>
                {
                    b.Navigation("ProjectMembers");

                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Auth.User", b =>
                {
                    b.Navigation("AuditLogs");

                    b.Navigation("ProjectInvites");

                    b.Navigation("ProjectMembers");
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Core.Flow", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Lanes");

                    b.Navigation("Links");

                    b.Navigation("MetadataItems");

                    b.Navigation("Nodes");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Core.FlowNode", b =>
                {
                    b.Navigation("IncomingLinks");

                    b.Navigation("OutgoingLinks");
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Core.Lane", b =>
                {
                    b.Navigation("Nodes");

                    b.Navigation("Stages");
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Core.Project", b =>
                {
                    b.Navigation("AiSettings");

                    b.Navigation("AuditLogs");

                    b.Navigation("EditorSettings");

                    b.Navigation("ExportSettings");

                    b.Navigation("Flows");

                    b.Navigation("Images");

                    b.Navigation("ProjectInvites");

                    b.Navigation("ProjectMembers");

                    b.Navigation("ProjectSettings");
                });

            modelBuilder.Entity("FlowDesigner.Domain.Entities.Core.Stage", b =>
                {
                    b.Navigation("Nodes");
                });
#pragma warning restore 612, 618
        }
    }
}
